service:
  name: multipart-forms-handling

# Add the serverless-webpack plugin
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  test:
    handler: first.hello
    events:
      - http:
          method: post
          path: test
custom:
  